# app/Dockerfile

FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

# test si la version du projet a changé
ADD https://api.github.com/repos/Slimanee/Itineraire-de-Vacances/git/refs/heads/main version.json

RUN git clone https://github.com/Slimanee/Itineraire-de-Vacances.git

WORKDIR /app/Itineraire-de-Vacances/

RUN pip3 install -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]