# app/Dockerfile

FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/Slimanee/Itineraire-de-Vacances.git .

RUN pip3 install -r requirements.txt

CMD ["uvicorn", "fastapi_main:app", "--host", "0.0.0.0", "--port", "8000"]